"""Neutral topic summarization for clustered stories (SPEC I3 §3).

When the clustering engine groups articles into a Topic, the AI service
synthesizes a short, neutral "what happened" overview from the articles' own
words. This is **extractive** (it selects representative sentences from the
source excerpts/titles rather than generating new claims), which keeps it
neutral and copyright-safe and lets it run fully offline and deterministically
in the demo. The result is clearly labeled AI-generated by the UI (I5).

Production swap: this same `/summarize` contract can be backed by an LLM later
(BLUEPRINT 2.8) without changing the main app — generation stays off the request
path and the output is stored/cached on the Topic, never computed per view.
"""

from __future__ import annotations

import math
import re
from collections import Counter
from dataclasses import dataclass

_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+")
_WORD = re.compile(r"[a-z0-9][a-z0-9'+-]*")
_WHITESPACE = re.compile(r"\s+")

# Small, generic English stop-word list — enough to weight content words without
# pulling a heavy NLP dependency into the image.
_STOPWORDS = frozenset(
    """a an and are as at be been being but by for from has have had he her his i in
    into is it its of on or our that the their them they this to was were what when
    which who will with you your we us not no but so than then there here also more
    most can could would should may might one two new now after before over out up
    about across against among around because been between during through while""".split()
)

_TLDR_MAX = 220
_SUMMARY_MAX = 600
_SUMMARY_SENTENCES = 3


@dataclass(frozen=True)
class ArticleInput:
    title: str
    excerpt: str = ""
    source: str = ""


def _clean(text: str) -> str:
    return _WHITESPACE.sub(" ", (text or "").strip())


def _split_sentences(text: str) -> list[str]:
    text = _clean(text)
    if not text:
        return []
    parts = _SENTENCE_SPLIT.split(text)
    out: list[str] = []
    for part in parts:
        part = part.strip()
        # Skip fragments too short to be a real sentence.
        if len(part) >= 24:
            out.append(part)
    return out


def _content_words(text: str) -> list[str]:
    return [w for w in _WORD.findall(text.lower()) if w not in _STOPWORDS and len(w) > 1]


def summarize(items: list[ArticleInput]) -> tuple[str, str]:
    """Return (tldr, summary). Deterministic and order-stable. `summary` is a
    short neutral overview; `tldr` is a single representative sentence."""
    # Gather candidate sentences from titles first (most information-dense), then
    # excerpts. De-duplicate by normalized text so multiple outlets repeating the
    # same headline don't dominate.
    candidates: list[str] = []
    seen: set[str] = set()
    for item in items:
        for sentence in [item.title, *_split_sentences(item.excerpt)]:
            sentence = _clean(sentence)
            if not sentence:
                continue
            key = sentence.lower()
            if key in seen:
                continue
            seen.add(key)
            candidates.append(sentence)

    if not candidates:
        return ("", "")

    # Term-frequency model over all candidate text → score each sentence by the
    # weight of the content words it contains (classic extractive summarization),
    # length-normalized so we don't just pick the longest sentence.
    freq: Counter[str] = Counter()
    for sentence in candidates:
        freq.update(_content_words(sentence))

    def score(sentence: str) -> float:
        words = _content_words(sentence)
        if not words:
            return 0.0
        # Length-normalized so we favour information density, not raw length.
        return sum(freq[w] for w in words) / math.sqrt(len(words))

    # Rank by score, break ties by original order (stable/deterministic).
    ranked = sorted(range(len(candidates)), key=lambda i: (-score(candidates[i]), i))

    # TL;DR: highest-scoring sentence, trimmed to a single line.
    tldr = candidates[ranked[0]]
    if len(tldr) > _TLDR_MAX:
        tldr = tldr[: _TLDR_MAX - 1].rstrip() + "…"

    # Summary: top sentences in ORIGINAL order so it reads coherently.
    chosen = sorted(ranked[:_SUMMARY_SENTENCES])
    pieces: list[str] = []
    total = 0
    for idx in chosen:
        sentence = candidates[idx]
        if not re.search(r"[.!?]$", sentence):
            sentence += "."
        if total + len(sentence) + 1 > _SUMMARY_MAX and pieces:
            break
        pieces.append(sentence)
        total += len(sentence) + 1
    summary = " ".join(pieces)

    return (tldr, summary)
