import { slugify } from '../../lib/slug';
import type { NormalizedGame } from './types';

/**
 * Local mock game catalog (SPEC I2 §2) — a broad, realistic dataset used by the
 * MockProvider in DEMO mode. NO network is ever touched: this bundled data IS
 * the "external source" in demo. In production the LiveProvider (IGDB→RAWG)
 * replaces it (BLUEPRINT 1.6); nothing else changes.
 *
 * ⚠️  MOCK / SEED DATA. Titles and metadata are real-world-style for a believable
 * demo, but release dates and several fields are approximate seed values — not a
 * source of truth. ~200 games spanning genres, platforms, years (1998–2027) and
 * every status, including Upcoming (future release) for the Upcoming view (I5).
 *
 * A handful are flagged `seed: false`: the provider can resolve them but they are
 * NOT pre-loaded into the DB, so the auto-resolve → auto-create path (the one I3
 * will use) is demonstrable distinct from a plain DB hit (SPEC I2 verify #5).
 */
export interface MockGameRecord extends NormalizedGame {
  /** false = resolvable via the provider but not bulk-seeded. Default true. */
  seed?: boolean;
}

// Platform presets (keep entries terse).
const PC = ['PC'];
const MULTI = ['PC', 'PS5', 'Xbox Series'];
const MULTI8 = ['PC', 'PS4', 'Xbox One'];
const MULTI_ALL = ['PC', 'PS5', 'PS4', 'Xbox Series', 'Xbox One'];
const SWITCH = ['Nintendo Switch'];

/** Compact builder for a released catalog entry; override anything via `extra`. */
function mk(
  name: string,
  year: number,
  developer: string,
  publisher: string,
  genres: string[],
  platforms: string[],
  extra: Partial<MockGameRecord> = {},
): MockGameRecord {
  const slug = extra.slug ?? slugify(name);
  return {
    externalId: slug,
    name,
    slug,
    status: 'released',
    releaseDate: `${year}-03-15`,
    developer,
    publisher,
    genres,
    platforms,
    externalRefs: { mock: slug },
    ...extra,
  };
}

const ph = (text: string, w = 600, h = 800): string =>
  `https://placehold.co/${w}x${h}/1b1b1f/f0b429?text=${encodeURIComponent(text)}`;

// ── Rich flagship entries (full metadata so later game pages look full) ───────
const RICH: MockGameRecord[] = [
  mk(
    'The Witcher 3: Wild Hunt',
    2015,
    'CD Projekt Red',
    'CD Projekt',
    ['RPG', 'Action'],
    MULTI_ALL,
    {
      summary: 'A story-driven open-world RPG following monster hunter Geralt of Rivia.',
      description:
        'The Witcher 3 sends Geralt across a war-torn open world to find Ciri, with branching quests, morally grey choices, and two acclaimed expansions.',
      tags: ['open-world', 'story-rich', 'choices-matter'],
      mode: ['singleplayer'],
      engine: 'REDengine 3',
      ageRatingSystem: 'PEGI',
      ageRatingValue: '18',
      series: 'The Witcher',
      steamAppId: 292030,
      hltbMainHours: 51,
      hltbCompletionistHours: 173,
      coverUrl: ph('The Witcher 3'),
      screenshots: [ph('Witcher 3 — 1', 1280, 720), ph('Witcher 3 — 2', 1280, 720)],
    },
  ),
  mk(
    'Elden Ring',
    2022,
    'FromSoftware',
    'Bandai Namco',
    ['RPG', 'Action', 'Souls-like'],
    MULTI_ALL,
    {
      summary: 'An open-world action RPG from FromSoftware and George R. R. Martin.',
      description:
        'Elden Ring blends FromSoftware combat with a vast open world, the Lands Between, full of optional dungeons, bosses and lore to discover.',
      tags: ['souls-like', 'open-world', 'difficult'],
      mode: ['singleplayer', 'co-op'],
      ageRatingSystem: 'PEGI',
      ageRatingValue: '16',
      steamAppId: 1245620,
      hltbMainHours: 58,
      hltbCompletionistHours: 133,
      coverUrl: ph('Elden Ring'),
      screenshots: [ph('Elden Ring — 1', 1280, 720), ph('Elden Ring — 2', 1280, 720)],
    },
  ),
  mk(
    'Red Dead Redemption 2',
    2018,
    'Rockstar Games',
    'Rockstar Games',
    ['Action', 'Adventure'],
    MULTI8,
    {
      summary: 'An epic tale of outlaw life in the dying days of the American frontier.',
      description:
        'As Arthur Morgan of the Van der Linde gang, survive a sprawling, detailed open world as the law and modernity close in.',
      tags: ['open-world', 'western', 'story-rich'],
      mode: ['singleplayer', 'multiplayer'],
      ageRatingSystem: 'PEGI',
      ageRatingValue: '18',
      steamAppId: 1174180,
      hltbMainHours: 50,
      hltbCompletionistHours: 180,
      coverUrl: ph('RDR2'),
    },
  ),
  mk(
    'God of War',
    2018,
    'Santa Monica Studio',
    'Sony Interactive Entertainment',
    ['Action', 'Adventure'],
    ['PC', 'PS4'],
    {
      summary: 'Kratos and his son Atreus journey through the realms of Norse myth.',
      tags: ['story-rich', 'mythology', 'single-player'],
      mode: ['singleplayer'],
      series: 'God of War',
      steamAppId: 1593500,
      hltbMainHours: 21,
      hltbCompletionistHours: 51,
      coverUrl: ph('God of War'),
    },
  ),
  mk(
    'Hades',
    2020,
    'Supergiant Games',
    'Supergiant Games',
    ['Roguelike', 'Action'],
    [...MULTI, 'Nintendo Switch', 'PS4', 'Xbox One'],
    {
      summary: 'A god-like rogue-like dungeon crawler escaping the Underworld.',
      tags: ['roguelike', 'indie', 'story-rich'],
      mode: ['singleplayer'],
      steamAppId: 1145360,
      hltbMainHours: 22,
      hltbCompletionistHours: 95,
      coverUrl: ph('Hades'),
    },
  ),
  mk(
    'Stardew Valley',
    2016,
    'ConcernedApe',
    'ConcernedApe',
    ['Simulation', 'RPG'],
    [...MULTI_ALL, 'Nintendo Switch'],
    {
      summary: 'Inherit a farm and build a life in a charming pixel-art countryside.',
      tags: ['farming-sim', 'cozy', 'pixel-graphics'],
      mode: ['singleplayer', 'co-op'],
      steamAppId: 413150,
      hltbMainHours: 53,
      hltbCompletionistHours: 159,
      coverUrl: ph('Stardew Valley'),
    },
  ),
  mk(
    'Hollow Knight',
    2017,
    'Team Cherry',
    'Team Cherry',
    ['Metroidvania', 'Action'],
    [...MULTI_ALL, 'Nintendo Switch'],
    {
      summary: 'Explore a vast ruined kingdom of insects and heroes.',
      tags: ['metroidvania', 'difficult', 'atmospheric'],
      mode: ['singleplayer'],
      steamAppId: 367520,
      hltbMainHours: 27,
      hltbCompletionistHours: 62,
      coverUrl: ph('Hollow Knight'),
    },
  ),
  mk('Disco Elysium', 2019, 'ZA/UM', 'ZA/UM', ['RPG'], [...MULTI_ALL, 'Nintendo Switch'], {
    summary: 'A groundbreaking detective RPG with no combat and total reactivity.',
    tags: ['story-rich', 'detective', 'choices-matter'],
    mode: ['singleplayer'],
    steamAppId: 632470,
    hltbMainHours: 21,
    hltbCompletionistHours: 56,
    coverUrl: ph('Disco Elysium'),
  }),
  mk(
    'DOOM Eternal',
    2020,
    'id Software',
    'Bethesda Softworks',
    ['Shooter', 'Action'],
    [...MULTI_ALL, 'Nintendo Switch'],
    {
      summary: 'Rip and tear through Hell in this relentless first-person shooter.',
      tags: ['fps', 'fast-paced', 'gore'],
      mode: ['singleplayer', 'multiplayer'],
      series: 'DOOM',
      steamAppId: 782330,
      coverUrl: ph('DOOM Eternal'),
    },
  ),
  mk(
    'Sekiro: Shadows Die Twice',
    2019,
    'FromSoftware',
    'Activision',
    ['Action', 'Souls-like'],
    MULTI8,
    {
      summary: 'A sengoku-era action game of posture-breaking swordplay and stealth.',
      tags: ['difficult', 'ninja', 'singleplayer'],
      mode: ['singleplayer'],
      steamAppId: 814380,
      coverUrl: ph('Sekiro'),
    },
  ),
  mk('Portal 2', 2011, 'Valve', 'Valve', ['Puzzle'], ['PC', 'PS3', 'Xbox 360'], {
    summary: 'A mind-bending first-person puzzler with a co-op campaign.',
    tags: ['puzzle', 'co-op', 'comedy'],
    mode: ['singleplayer', 'co-op'],
    steamAppId: 620,
    coverUrl: ph('Portal 2'),
  }),
  mk(
    'Baldur’s Gate 3',
    2023,
    'Larian Studios',
    'Larian Studios',
    ['RPG', 'Turn-Based'],
    ['PC', 'PS5', 'Xbox Series'],
    {
      slug: 'baldurs-gate-3',
      summary: 'A party-based RPG set in the world of Dungeons & Dragons.',
      tags: ['crpg', 'turn-based', 'choices-matter'],
      mode: ['singleplayer', 'co-op'],
      steamAppId: 1086940,
      coverUrl: ph('Baldur’s Gate 3'),
    },
  ),
  mk(
    'Cyberpunk 2077',
    2020,
    'CD Projekt Red',
    'CD Projekt',
    ['RPG', 'Action'],
    ['PC', 'PS5', 'Xbox Series'],
    {
      slug: 'cyberpunk-2077',
      summary: 'Open-world action RPG set in the dystopian Night City.',
      tags: ['open-world', 'cyberpunk', 'story-rich'],
      mode: ['singleplayer'],
      steamAppId: 1091500,
      coverUrl: ph('Cyberpunk 2077'),
    },
  ),
];

// ── Broad catalog (terse) ────────────────────────────────────────────────────
const CATALOG: MockGameRecord[] = [
  // RPG / action
  mk(
    'Mass Effect 2',
    2010,
    'BioWare',
    'Electronic Arts',
    ['RPG', 'Shooter'],
    ['PC', 'PS3', 'Xbox 360'],
  ),
  mk('Mass Effect Legendary Edition', 2021, 'BioWare', 'Electronic Arts', ['RPG'], MULTI8),
  mk('Dragon Age: Inquisition', 2014, 'BioWare', 'Electronic Arts', ['RPG'], MULTI8),
  mk(
    'The Elder Scrolls V: Skyrim',
    2011,
    'Bethesda Game Studios',
    'Bethesda Softworks',
    ['RPG'],
    MULTI_ALL,
    { steamAppId: 489830 },
  ),
  mk(
    'Fallout: New Vegas',
    2010,
    'Obsidian Entertainment',
    'Bethesda Softworks',
    ['RPG'],
    ['PC', 'PS3', 'Xbox 360'],
  ),
  mk('Fallout 4', 2015, 'Bethesda Game Studios', 'Bethesda Softworks', ['RPG'], MULTI8),
  mk(
    'Persona 5 Royal',
    2019,
    'Atlus',
    'Sega',
    ['RPG', 'Turn-Based'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'Final Fantasy VII Remake',
    2020,
    'Square Enix',
    'Square Enix',
    ['RPG', 'Action'],
    ['PC', 'PS5', 'PS4'],
  ),
  mk('Final Fantasy XVI', 2023, 'Square Enix', 'Square Enix', ['RPG', 'Action'], ['PC', 'PS5']),
  mk('Monster Hunter: World', 2018, 'Capcom', 'Capcom', ['Action', 'RPG'], MULTI8, {
    steamAppId: 582010,
  }),
  mk(
    'Monster Hunter Rise',
    2021,
    'Capcom',
    'Capcom',
    ['Action', 'RPG'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk('Nioh 2', 2020, 'Team Ninja', 'Koei Tecmo', ['Action', 'Souls-like'], ['PC', 'PS5', 'PS4']),
  mk('Dark Souls III', 2016, 'FromSoftware', 'Bandai Namco', ['Souls-like', 'Action'], MULTI8, {
    series: 'Dark Souls',
  }),
  mk(
    'Bloodborne',
    2015,
    'FromSoftware',
    'Sony Interactive Entertainment',
    ['Souls-like', 'Action'],
    ['PS4'],
  ),
  mk(
    'Horizon Zero Dawn',
    2017,
    'Guerrilla Games',
    'Sony Interactive Entertainment',
    ['RPG', 'Action'],
    ['PC', 'PS4'],
  ),
  mk(
    'Horizon Forbidden West',
    2022,
    'Guerrilla Games',
    'Sony Interactive Entertainment',
    ['RPG', 'Action'],
    ['PC', 'PS5', 'PS4'],
  ),
  mk(
    'Ghost of Tsushima',
    2020,
    'Sucker Punch Productions',
    'Sony Interactive Entertainment',
    ['Action', 'Adventure'],
    ['PC', 'PS5', 'PS4'],
  ),
  mk('Assassin’s Creed Odyssey', 2018, 'Ubisoft', 'Ubisoft', ['RPG', 'Action'], MULTI8, {
    series: 'Assassin’s Creed',
  }),
  mk('Assassin’s Creed Valhalla', 2020, 'Ubisoft', 'Ubisoft', ['RPG', 'Action'], MULTI_ALL, {
    series: 'Assassin’s Creed',
  }),
  mk(
    'The Witcher 2: Assassins of Kings',
    2011,
    'CD Projekt Red',
    'CD Projekt',
    ['RPG'],
    ['PC', 'Xbox 360'],
    { series: 'The Witcher' },
  ),
  mk(
    'Divinity: Original Sin 2',
    2017,
    'Larian Studios',
    'Larian Studios',
    ['RPG', 'Turn-Based'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk('Pillars of Eternity', 2015, 'Obsidian Entertainment', 'Paradox Interactive', ['RPG'], PC),
  mk('NieR: Automata', 2017, 'PlatinumGames', 'Square Enix', ['Action', 'RPG'], MULTI8),
  mk('Kingdom Come: Deliverance', 2018, 'Warhorse Studios', 'Deep Silver', ['RPG'], MULTI8),
  mk('Dragon’s Dogma 2', 2024, 'Capcom', 'Capcom', ['RPG', 'Action'], MULTI),
  mk('Like a Dragon: Infinite Wealth', 2024, 'Ryu Ga Gotoku Studio', 'Sega', ['RPG'], MULTI_ALL),
  mk('Yakuza 0', 2015, 'Ryu Ga Gotoku Studio', 'Sega', ['Action', 'Adventure'], MULTI_ALL),
  mk(
    'Octopath Traveler',
    2018,
    'Square Enix',
    'Square Enix',
    ['RPG', 'Turn-Based'],
    [...PC, 'Nintendo Switch'],
  ),

  // Shooters / FPS
  mk('Half-Life 2', 2004, 'Valve', 'Valve', ['Shooter'], PC, {
    steamAppId: 220,
    series: 'Half-Life',
  }),
  mk('Half-Life: Alyx', 2020, 'Valve', 'Valve', ['Shooter', 'VR'], PC, { series: 'Half-Life' }),
  mk('Counter-Strike 2', 2023, 'Valve', 'Valve', ['Shooter'], PC, { steamAppId: 730 }),
  mk('DOOM', 2016, 'id Software', 'Bethesda Softworks', ['Shooter', 'Action'], MULTI8, {
    series: 'DOOM',
  }),
  mk(
    'Wolfenstein II: The New Colossus',
    2017,
    'MachineGames',
    'Bethesda Softworks',
    ['Shooter'],
    MULTI8,
  ),
  mk('Titanfall 2', 2016, 'Respawn Entertainment', 'Electronic Arts', ['Shooter'], MULTI8),
  mk(
    'Apex Legends',
    2019,
    'Respawn Entertainment',
    'Electronic Arts',
    ['Shooter', 'Battle Royale'],
    MULTI_ALL,
  ),
  mk(
    'Overwatch 2',
    2022,
    'Blizzard Entertainment',
    'Blizzard Entertainment',
    ['Shooter'],
    MULTI_ALL,
  ),
  mk('Destiny 2', 2017, 'Bungie', 'Bungie', ['Shooter', 'MMO'], MULTI_ALL),
  mk('Call of Duty: Modern Warfare', 2019, 'Infinity Ward', 'Activision', ['Shooter'], MULTI8),
  mk('Battlefield 1', 2016, 'DICE', 'Electronic Arts', ['Shooter'], MULTI8),
  mk(
    'Borderlands 2',
    2012,
    'Gearbox Software',
    '2K Games',
    ['Shooter', 'RPG'],
    ['PC', 'PS3', 'Xbox 360'],
  ),
  mk('Borderlands 3', 2019, 'Gearbox Software', '2K Games', ['Shooter', 'RPG'], MULTI8),
  mk('Tom Clancy’s Rainbow Six Siege', 2015, 'Ubisoft', 'Ubisoft', ['Shooter'], MULTI_ALL),
  mk('Far Cry 5', 2018, 'Ubisoft', 'Ubisoft', ['Shooter', 'Action'], MULTI8),
  mk('Metro Exodus', 2019, '4A Games', 'Deep Silver', ['Shooter'], MULTI_ALL),
  mk(
    'BioShock Infinite',
    2013,
    'Irrational Games',
    '2K Games',
    ['Shooter'],
    ['PC', 'PS3', 'Xbox 360'],
  ),
  mk(
    'Halo Infinite',
    2021,
    '343 Industries',
    'Xbox Game Studios',
    ['Shooter'],
    ['PC', 'Xbox Series', 'Xbox One'],
  ),
  mk('Left 4 Dead 2', 2009, 'Valve', 'Valve', ['Shooter'], ['PC', 'Xbox 360'], { steamAppId: 550 }),
  mk(
    'Deathloop',
    2021,
    'Arkane Studios',
    'Bethesda Softworks',
    ['Shooter', 'Action'],
    ['PC', 'PS5'],
  ),
  mk('Hunt: Showdown', 2019, 'Crytek', 'Crytek', ['Shooter'], MULTI8),
  mk(
    'Insurgency: Sandstorm',
    2018,
    'New World Interactive',
    'Focus Entertainment',
    ['Shooter'],
    MULTI8,
  ),

  // Indie
  mk(
    'Celeste',
    2018,
    'Maddy Makes Games',
    'Maddy Makes Games',
    ['Platformer', 'Indie'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'Undertale',
    2015,
    'Toby Fox',
    'Toby Fox',
    ['RPG', 'Indie'],
    [...PC, 'PS4', 'Nintendo Switch'],
  ),
  mk(
    'Cuphead',
    2017,
    'Studio MDHR',
    'Studio MDHR',
    ['Platformer', 'Indie'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'Dead Cells',
    2018,
    'Motion Twin',
    'Motion Twin',
    ['Roguelike', 'Metroidvania'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'Hyper Light Drifter',
    2016,
    'Heart Machine',
    'Heart Machine',
    ['Action', 'Indie'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'Ori and the Blind Forest',
    2015,
    'Moon Studios',
    'Xbox Game Studios',
    ['Metroidvania'],
    ['PC', 'Xbox One', 'Nintendo Switch'],
  ),
  mk(
    'Ori and the Will of the Wisps',
    2020,
    'Moon Studios',
    'Xbox Game Studios',
    ['Metroidvania'],
    ['PC', 'Xbox One', 'Nintendo Switch'],
  ),
  mk(
    'Slay the Spire',
    2019,
    'Mega Crit',
    'Mega Crit',
    ['Roguelike', 'Card'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'Into the Breach',
    2018,
    'Subset Games',
    'Subset Games',
    ['Strategy', 'Indie'],
    [...PC, 'Nintendo Switch'],
  ),
  mk('FTL: Faster Than Light', 2012, 'Subset Games', 'Subset Games', ['Strategy', 'Roguelike'], PC),
  mk(
    'Outer Wilds',
    2019,
    'Mobius Digital',
    'Annapurna Interactive',
    ['Adventure', 'Indie'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'Return of the Obra Dinn',
    2018,
    'Lucas Pope',
    '3909',
    ['Puzzle', 'Indie'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk('Inside', 2016, 'Playdead', 'Playdead', ['Platformer', 'Puzzle'], MULTI8),
  mk('Limbo', 2010, 'Playdead', 'Playdead', ['Platformer', 'Puzzle'], ['PC', 'Xbox 360']),
  mk(
    'Spelunky 2',
    2020,
    'Mossmouth',
    'Mossmouth',
    ['Roguelike', 'Platformer'],
    ['PC', 'PS4', 'Nintendo Switch'],
  ),
  mk('Terraria', 2011, 'Re-Logic', 'Re-Logic', ['Sandbox', 'Adventure'], MULTI_ALL, {
    steamAppId: 105600,
  }),
  mk(
    'Vampire Survivors',
    2022,
    'poncle',
    'poncle',
    ['Roguelike', 'Indie'],
    [...MULTI_ALL, 'Nintendo Switch'],
    { steamAppId: 1794680 },
  ),
  mk(
    'Cult of the Lamb',
    2022,
    'Massive Monster',
    'Devolver Digital',
    ['Roguelike', 'Simulation'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'Hotline Miami',
    2012,
    'Dennaton Games',
    'Devolver Digital',
    ['Action', 'Indie'],
    ['PC', 'PS4'],
  ),
  mk(
    'Katana ZERO',
    2019,
    'Askiisoft',
    'Devolver Digital',
    ['Action', 'Indie'],
    [...PC, 'Nintendo Switch', 'Xbox One'],
  ),
  mk('Tunic', 2022, 'Andrew Shouldice', 'Finji', ['Adventure', 'Indie'], MULTI_ALL),
  mk('Pizza Tower', 2023, 'Tour De Pizza', 'Tour De Pizza', ['Platformer', 'Indie'], PC),
  mk(
    'Loop Hero',
    2021,
    'Four Quarters',
    'Devolver Digital',
    ['Roguelike', 'Strategy'],
    [...PC, 'Nintendo Switch'],
  ),
  mk(
    'GRIS',
    2018,
    'Nomada Studio',
    'Devolver Digital',
    ['Platformer', 'Indie'],
    [...PC, 'Nintendo Switch'],
  ),
  mk(
    'Inscryption',
    2021,
    'Daniel Mullins Games',
    'Devolver Digital',
    ['Card', 'Roguelike'],
    [...PC, 'PS5', 'PS4'],
  ),
  mk('Balatro', 2024, 'LocalThunk', 'Playstack', ['Card', 'Roguelike'], MULTI_ALL),

  // Strategy / sim
  mk(
    'Sid Meier’s Civilization VI',
    2016,
    'Firaxis Games',
    '2K Games',
    ['Strategy', '4X'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk('Sid Meier’s Civilization V', 2010, 'Firaxis Games', '2K Games', ['Strategy', '4X'], PC),
  mk('XCOM 2', 2016, 'Firaxis Games', '2K Games', ['Strategy', 'Turn-Based'], MULTI8),
  mk(
    'Cities: Skylines',
    2015,
    'Colossal Order',
    'Paradox Interactive',
    ['Simulation', 'Strategy'],
    MULTI8,
  ),
  mk(
    'Cities: Skylines II',
    2023,
    'Colossal Order',
    'Paradox Interactive',
    ['Simulation', 'Strategy'],
    MULTI,
  ),
  mk(
    'Crusader Kings III',
    2020,
    'Paradox Development Studio',
    'Paradox Interactive',
    ['Strategy', 'Grand Strategy'],
    MULTI,
  ),
  mk(
    'Stellaris',
    2016,
    'Paradox Development Studio',
    'Paradox Interactive',
    ['Strategy', '4X'],
    MULTI8,
  ),
  mk(
    'Hearts of Iron IV',
    2016,
    'Paradox Development Studio',
    'Paradox Interactive',
    ['Strategy', 'Grand Strategy'],
    PC,
  ),
  mk('Total War: Three Kingdoms', 2019, 'Creative Assembly', 'Sega', ['Strategy'], PC),
  mk('Total War: Warhammer III', 2022, 'Creative Assembly', 'Sega', ['Strategy'], PC),
  mk(
    'Age of Empires IV',
    2021,
    'Relic Entertainment',
    'Xbox Game Studios',
    ['Strategy', 'RTS'],
    ['PC', 'Xbox Series'],
  ),
  mk('Frostpunk', 2018, '11 bit studios', '11 bit studios', ['Strategy', 'Survival'], MULTI8),
  mk('RimWorld', 2018, 'Ludeon Studios', 'Ludeon Studios', ['Simulation', 'Strategy'], MULTI),
  mk(
    'Factorio',
    2020,
    'Wube Software',
    'Wube Software',
    ['Simulation', 'Strategy'],
    [...PC, 'Nintendo Switch'],
    { steamAppId: 427520 },
  ),
  mk('Oxygen Not Included', 2019, 'Klei Entertainment', 'Klei Entertainment', ['Simulation'], PC),
  mk(
    'Don’t Starve Together',
    2016,
    'Klei Entertainment',
    'Klei Entertainment',
    ['Survival'],
    MULTI_ALL,
  ),
  mk(
    'They Are Billions',
    2019,
    'Numantian Games',
    'Numantian Games',
    ['Strategy', 'Survival'],
    MULTI8,
  ),
  mk('Anno 1800', 2019, 'Ubisoft', 'Ubisoft', ['Strategy', 'Simulation'], MULTI),
  mk(
    'Tropico 6',
    2019,
    'Limbic Entertainment',
    'Kalypso Media',
    ['Strategy', 'Simulation'],
    MULTI_ALL,
  ),
  mk(
    'Manor Lords',
    2024,
    'Slavic Magic',
    'Hooded Horse',
    ['Strategy', 'City-Builder'],
    ['PC', 'Xbox Series'],
    { status: 'early_access' },
  ),

  // Multiplayer / live
  mk('Fortnite', 2017, 'Epic Games', 'Epic Games', ['Battle Royale', 'Shooter'], MULTI_ALL),
  mk('VALORANT', 2020, 'Riot Games', 'Riot Games', ['Shooter'], MULTI),
  mk('League of Legends', 2009, 'Riot Games', 'Riot Games', ['MOBA'], PC),
  mk('Dota 2', 2013, 'Valve', 'Valve', ['MOBA'], PC, { steamAppId: 570 }),
  mk('Rocket League', 2015, 'Psyonix', 'Psyonix', ['Sports'], MULTI_ALL),
  mk('Fall Guys', 2020, 'Mediatonic', 'Epic Games', ['Party'], MULTI_ALL),
  mk(
    'Among Us',
    2018,
    'InnerSloth',
    'InnerSloth',
    ['Party', 'Indie'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk('Sea of Thieves', 2018, 'Rare', 'Xbox Game Studios', ['Adventure', 'Co-op'], MULTI),
  mk(
    'Deep Rock Galactic',
    2020,
    'Ghost Ship Games',
    'Coffee Stain Publishing',
    ['Shooter', 'Co-op'],
    MULTI_ALL,
  ),
  mk('Phasmophobia', 2020, 'Kinetic Games', 'Kinetic Games', ['Horror', 'Co-op'], MULTI, {
    status: 'early_access',
  }),
  mk(
    'Valheim',
    2021,
    'Iron Gate Studio',
    'Coffee Stain Publishing',
    ['Survival', 'Co-op'],
    ['PC', 'Xbox Series', 'Xbox One'],
    { status: 'early_access', steamAppId: 892970 },
  ),
  mk('Rust', 2018, 'Facepunch Studios', 'Facepunch Studios', ['Survival'], MULTI_ALL, {
    steamAppId: 252490,
  }),
  mk(
    'Warframe',
    2013,
    'Digital Extremes',
    'Digital Extremes',
    ['Shooter', 'MMO'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'Path of Exile',
    2013,
    'Grinding Gear Games',
    'Grinding Gear Games',
    ['RPG', 'Action'],
    MULTI8,
  ),
  mk('Genshin Impact', 2020, 'HoYoverse', 'HoYoverse', ['RPG', 'Action'], ['PC', 'PS5', 'PS4']),
  mk(
    'Helldivers 2',
    2024,
    'Arrowhead Game Studios',
    'Sony Interactive Entertainment',
    ['Shooter', 'Co-op'],
    ['PC', 'PS5'],
  ),
  mk('Lethal Company', 2023, 'Zeekerss', 'Zeekerss', ['Horror', 'Co-op'], PC, {
    status: 'early_access',
  }),

  // Adventure / narrative / action
  mk(
    'Death Stranding',
    2019,
    'Kojima Productions',
    'Sony Interactive Entertainment',
    ['Action', 'Adventure'],
    ['PC', 'PS5', 'PS4'],
  ),
  mk(
    'Detroit: Become Human',
    2018,
    'Quantic Dream',
    'Sony Interactive Entertainment',
    ['Adventure'],
    ['PC', 'PS4'],
  ),
  mk('Life is Strange', 2015, 'Dontnod Entertainment', 'Square Enix', ['Adventure'], MULTI8),
  mk('Firewatch', 2016, 'Campo Santo', 'Panic', ['Adventure', 'Indie'], MULTI8),
  mk(
    'What Remains of Edith Finch',
    2017,
    'Giant Sparrow',
    'Annapurna Interactive',
    ['Adventure', 'Indie'],
    MULTI_ALL,
  ),
  mk(
    'It Takes Two',
    2021,
    'Hazelight Studios',
    'Electronic Arts',
    ['Co-op', 'Adventure'],
    MULTI_ALL,
  ),
  mk('A Way Out', 2018, 'Hazelight Studios', 'Electronic Arts', ['Co-op', 'Adventure'], MULTI8),
  mk('Subnautica', 2018, 'Unknown Worlds', 'Unknown Worlds', ['Survival', 'Adventure'], MULTI_ALL),
  mk('No Man’s Sky', 2016, 'Hello Games', 'Hello Games', ['Survival', 'Adventure'], MULTI_ALL, {
    steamAppId: 275850,
  }),
  mk('Control', 2019, 'Remedy Entertainment', '505 Games', ['Action', 'Adventure'], MULTI_ALL),
  mk('Alan Wake 2', 2023, 'Remedy Entertainment', 'Epic Games', ['Horror', 'Action'], MULTI),
  mk('Resident Evil 4', 2023, 'Capcom', 'Capcom', ['Horror', 'Action'], MULTI, {
    series: 'Resident Evil',
  }),
  mk('Resident Evil Village', 2021, 'Capcom', 'Capcom', ['Horror', 'Action'], MULTI_ALL, {
    series: 'Resident Evil',
  }),
  mk('Devil May Cry 5', 2019, 'Capcom', 'Capcom', ['Action'], MULTI_ALL),
  mk('Street Fighter 6', 2023, 'Capcom', 'Capcom', ['Fighting'], MULTI),
  mk('Tekken 8', 2024, 'Bandai Namco Studios', 'Bandai Namco', ['Fighting'], MULTI),
  mk(
    'Mortal Kombat 1',
    2023,
    'NetherRealm Studios',
    'Warner Bros. Games',
    ['Fighting'],
    [...MULTI, 'Nintendo Switch'],
  ),
  mk('Guilty Gear -Strive-', 2021, 'Arc System Works', 'Arc System Works', ['Fighting'], MULTI_ALL),

  // Nintendo / first-party
  mk('Super Mario Odyssey', 2017, 'Nintendo', 'Nintendo', ['Platformer'], SWITCH),
  mk(
    'The Legend of Zelda: Breath of the Wild',
    2017,
    'Nintendo',
    'Nintendo',
    ['Action', 'Adventure'],
    SWITCH,
    { series: 'The Legend of Zelda' },
  ),
  mk(
    'The Legend of Zelda: Tears of the Kingdom',
    2023,
    'Nintendo',
    'Nintendo',
    ['Action', 'Adventure'],
    SWITCH,
    { series: 'The Legend of Zelda' },
  ),
  mk('Super Smash Bros. Ultimate', 2018, 'Bandai Namco Studios', 'Nintendo', ['Fighting'], SWITCH),
  mk('Animal Crossing: New Horizons', 2020, 'Nintendo', 'Nintendo', ['Simulation'], SWITCH),
  mk('Splatoon 3', 2022, 'Nintendo', 'Nintendo', ['Shooter'], SWITCH),
  mk('Metroid Dread', 2021, 'MercurySteam', 'Nintendo', ['Metroidvania'], SWITCH),
  mk('Mario Kart 8 Deluxe', 2017, 'Nintendo', 'Nintendo', ['Racing'], SWITCH),
  mk('Pokémon Scarlet and Violet', 2022, 'Game Freak', 'Nintendo', ['RPG'], SWITCH),
  mk(
    'Fire Emblem: Three Houses',
    2019,
    'Intelligent Systems',
    'Nintendo',
    ['Strategy', 'RPG'],
    SWITCH,
  ),
  mk('Xenoblade Chronicles 3', 2022, 'Monolith Soft', 'Nintendo', ['RPG'], SWITCH),

  // Racing / sports
  mk(
    'Forza Horizon 5',
    2021,
    'Playground Games',
    'Xbox Game Studios',
    ['Racing'],
    ['PC', 'Xbox Series', 'Xbox One'],
  ),
  mk(
    'Gran Turismo 7',
    2022,
    'Polyphony Digital',
    'Sony Interactive Entertainment',
    ['Racing'],
    ['PS5', 'PS4'],
  ),
  mk('F1 23', 2023, 'Codemasters', 'EA Sports', ['Racing', 'Sports'], MULTI_ALL),
  mk(
    'EA Sports FC 24',
    2023,
    'EA Sports',
    'Electronic Arts',
    ['Sports'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'NBA 2K24',
    2023,
    'Visual Concepts',
    '2K Sports',
    ['Sports'],
    [...MULTI_ALL, 'Nintendo Switch'],
  ),
  mk(
    'Microsoft Flight Simulator',
    2020,
    'Asobo Studio',
    'Xbox Game Studios',
    ['Simulation'],
    ['PC', 'Xbox Series'],
  ),
  mk('Need for Speed Heat', 2019, 'Ghost Games', 'Electronic Arts', ['Racing'], MULTI8),

  // Blizzard / classics / sandbox
  mk(
    'Diablo II: Resurrected',
    2021,
    'Blizzard Entertainment',
    'Blizzard Entertainment',
    ['RPG', 'Action'],
    MULTI_ALL,
    { series: 'Diablo' },
  ),
  mk(
    'Diablo III',
    2012,
    'Blizzard Entertainment',
    'Blizzard Entertainment',
    ['RPG', 'Action'],
    MULTI8,
    { series: 'Diablo' },
  ),
  mk(
    'Diablo IV',
    2023,
    'Blizzard Entertainment',
    'Blizzard Entertainment',
    ['RPG', 'Action'],
    MULTI_ALL,
    { series: 'Diablo' },
  ),
  mk(
    'World of Warcraft',
    2004,
    'Blizzard Entertainment',
    'Blizzard Entertainment',
    ['MMO', 'RPG'],
    PC,
  ),
  mk(
    'StarCraft II: Wings of Liberty',
    2010,
    'Blizzard Entertainment',
    'Blizzard Entertainment',
    ['Strategy', 'RTS'],
    PC,
  ),
  mk('The Sims 4', 2014, 'Maxis', 'Electronic Arts', ['Simulation'], MULTI_ALL),
  mk(
    'Grand Theft Auto V',
    2013,
    'Rockstar North',
    'Rockstar Games',
    ['Action', 'Adventure'],
    MULTI_ALL,
    { series: 'Grand Theft Auto', steamAppId: 271590 },
  ),
  mk(
    'Grand Theft Auto: San Andreas',
    2004,
    'Rockstar North',
    'Rockstar Games',
    ['Action', 'Adventure'],
    ['PC', 'PS2', 'Xbox'],
    { series: 'Grand Theft Auto' },
  ),
  mk('Minecraft', 2011, 'Mojang Studios', 'Mojang Studios', ['Sandbox', 'Survival'], MULTI_ALL),
  mk('Portal', 2007, 'Valve', 'Valve', ['Puzzle'], PC, { steamAppId: 400, series: 'Portal' }),
  mk('Team Fortress 2', 2007, 'Valve', 'Valve', ['Shooter'], PC, { steamAppId: 440 }),
  mk('Half-Life', 1998, 'Valve', 'Sierra Studios', ['Shooter'], PC, { series: 'Half-Life' }),
  mk('World of Goo', 2008, '2D Boy', '2D Boy', ['Puzzle', 'Indie'], [...PC, 'Nintendo Switch']),
  mk('Braid', 2008, 'Number None', 'Number None', ['Puzzle', 'Platformer'], ['PC', 'Xbox 360']),
  mk('Bastion', 2011, 'Supergiant Games', 'Supergiant Games', ['Action', 'Indie'], MULTI_ALL),
  mk('Transistor', 2014, 'Supergiant Games', 'Supergiant Games', ['Action', 'RPG'], ['PC', 'PS4']),

  // ── Upcoming (future release relative to demo date 2026-06-14) ─────────────
  mk(
    'Grand Theft Auto VI',
    2026,
    'Rockstar Games',
    'Rockstar Games',
    ['Action', 'Adventure'],
    ['PS5', 'Xbox Series'],
    {
      status: 'in_development',
      releaseDate: '2026-11-19',
      series: 'Grand Theft Auto',
      summary: 'The next chapter in the Grand Theft Auto series, returning to Vice City.',
    },
  ),
  mk(
    'Hollow Knight: Silksong',
    2026,
    'Team Cherry',
    'Team Cherry',
    ['Metroidvania', 'Action'],
    [...MULTI_ALL, 'Nintendo Switch'],
    {
      status: 'in_development',
      releaseDate: '2026-09-30',
      series: 'Hollow Knight',
      summary: 'Play as Hornet in a haunted kingdom in this sequel to Hollow Knight.',
    },
  ),
  mk(
    'Hades II',
    2026,
    'Supergiant Games',
    'Supergiant Games',
    ['Roguelike', 'Action'],
    [...PC, 'Nintendo Switch'],
    {
      status: 'early_access',
      releaseDate: '2026-12-01',
      series: 'Hades',
      summary: 'Battle the Titan of Time as the Princess of the Underworld.',
    },
  ),
  mk(
    'Fable',
    2026,
    'Playground Games',
    'Xbox Game Studios',
    ['RPG', 'Action'],
    ['PC', 'Xbox Series'],
    {
      status: 'in_development',
      releaseDate: '2026-10-08',
      series: 'Fable',
    },
  ),
  mk(
    'Metroid Prime 4: Beyond',
    2026,
    'Retro Studios',
    'Nintendo',
    ['Shooter', 'Adventure'],
    SWITCH,
    {
      status: 'in_development',
      releaseDate: '2026-08-20',
      series: 'Metroid',
    },
  ),
  mk(
    'The Elder Scrolls VI',
    2027,
    'Bethesda Game Studios',
    'Bethesda Softworks',
    ['RPG'],
    ['PC', 'Xbox Series'],
    {
      status: 'announced',
      releaseDate: undefined,
      series: 'The Elder Scrolls',
      summary: 'The long-awaited next mainline Elder Scrolls RPG.',
    },
  ),
  mk(
    'Death Stranding 2: On the Beach',
    2026,
    'Kojima Productions',
    'Sony Interactive Entertainment',
    ['Action', 'Adventure'],
    ['PS5'],
    {
      status: 'in_development',
      releaseDate: '2026-06-26',
    },
  ),

  // Upcoming + resolvable-but-not-seeded (auto-resolve demo, SPEC verify #5)
  mk('The Witcher IV', 2027, 'CD Projekt Red', 'CD Projekt', ['RPG'], MULTI, {
    status: 'announced',
    releaseDate: undefined,
    series: 'The Witcher',
    seed: false,
  }),
  mk(
    'Ghost of Yotei',
    2026,
    'Sucker Punch Productions',
    'Sony Interactive Entertainment',
    ['Action', 'Adventure'],
    ['PS5'],
    {
      status: 'in_development',
      releaseDate: '2026-10-02',
      seed: false,
    },
  ),
  mk('Crimson Desert', 2026, 'Pearl Abyss', 'Pearl Abyss', ['RPG', 'Action'], MULTI, {
    status: 'in_development',
    releaseDate: '2026-12-15',
    seed: false,
  }),
  mk('Light No Fire', 2027, 'Hello Games', 'Hello Games', ['Survival', 'Adventure'], MULTI, {
    status: 'announced',
    releaseDate: undefined,
    seed: false,
  }),
  mk('Pragmata', 2026, 'Capcom', 'Capcom', ['Action', 'Adventure'], MULTI, {
    status: 'in_development',
    releaseDate: '2026-09-08',
    seed: false,
  }),
  mk('Project 007', 2027, 'IO Interactive', 'IO Interactive', ['Action', 'Adventure'], MULTI, {
    status: 'announced',
    releaseDate: undefined,
    seed: false,
  }),

  // ── Delisted ──────────────────────────────────────────────────────────────
  mk('P.T.', 2014, 'Kojima Productions', 'Konami', ['Horror'], ['PS4'], { status: 'delisted' }),
  mk('Marvel’s Avengers', 2020, 'Crystal Dynamics', 'Square Enix', ['Action'], MULTI8, {
    status: 'delisted',
  }),
  mk('The Culling', 2016, 'Xaviant', 'Xaviant', ['Battle Royale'], ['PC', 'Xbox One'], {
    status: 'delisted',
  }),
  mk('Knockout City', 2021, 'Velan Studios', 'Electronic Arts', ['Sports'], MULTI_ALL, {
    status: 'delisted',
  }),
  mk(
    'Scott Pilgrim vs. The World: The Game',
    2010,
    'Ubisoft',
    'Ubisoft',
    ['Action'],
    ['PS3', 'Xbox 360'],
    { status: 'delisted' },
  ),
];

/**
 * The full mock dataset (rich + broad). Some `seed: false` entries are
 * resolvable by the provider but not bulk-loaded (auto-resolve demo).
 */
export const MOCK_GAMES: MockGameRecord[] = [...RICH, ...CATALOG];
